language: python
services:
  - docker
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
after_success:
  - make docker_build
deploy:
  provider: heroku
  app: infinite-taiga-47232
  api_key: ${HEROKU_API_KEY}
